version: "3.6"
services:
  server:
    image: docker.nist.gov:4567/eldst/eerc
    hostname: eerc
    networks:
      - traefik_net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.http.routers.eerc_router_http.rule=Host(`eerc-test.el.nist.gov`)"
        - "traefik.http.routers.eerc_router_http.entrypoints=web"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.eerc_router_http.middlewares=https_redirect"
        - "traefik.http.routers.eerc_router_https.rule=Host(`eerc-test.el.nist.gov`)"
        - "traefik.http.routers.eerc_router_https.entrypoints=websecure"
        - "traefik.http.routers.eerc_router_https.tls"
        - "traefik.http.services.eerc_service.loadbalancer.server.port=80"

networks:
  traefik_net:
    external: true
