#!/bin/bash

TEMP_BRANCH=temp-split
PAGES_BRANCH=nist-pages
MASTER_REMOTE=origin
PAGES_REMOTE=origin
BUILD_DIR=build

die() {
  echo "$@" >> /dev/stderr
  exit 1
}

cleanup() {
  git branch -D "$TEMP_BRANCH" >/dev/null 2>&1  # Ignore errors; branch probably doesn't exist anyway 
  git branch -D "$PAGES_BRANCH" >/dev/null 2>&1  # Ignore errors; branch probably doesn't exist anyway
  #rm -rf build
}

if [ ! -d .git ]; then
  die "You must run this from the root of the master repo"
fi

cleanup

npm run build || die "'npm run build' failed" 
git checkout -b $TEMP_BRANCH || die "Could not create branch $TEMP_BRANCH" # should bring over build directory
git add -f $BUILD_DIR || die "Could not add $BUILD_DIR to $TEMP_BRANCH"
git commit -m "irrelevant commit for $PAGES_BRANCH generation" || die "Could not commit to $TEMP_BRANCH"
git subtree split --prefix build -b "$PAGES_BRANCH" || die "'git subtree split' failed"
git checkout master || die "'git checkout master' failed"
#git push -f "${PAGES_REMOTE} ${PAGES_BRANCH}:${PAGES_BRANCH}" || die "'git push' failed"

#cleanup

exit 0
